### ISSUE TITLE
Precompiling raises `TypeError: nil not allowed`

### ISSUE THREAD

**Issue by nicooga** [railsware/js-routes#220]
Using version 1.3.3. When running `rake assets:precompile` raises `TypeError: nil not allowed`. This is the partial bactrace:

~~~
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:99:in `generate'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:99:in `stringify'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:33:in `encode'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:20:in `encode'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/js-routes-1.3.3/lib/js_routes.rb:86:in `json'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/js-routes-1.3.3/lib/js_routes.rb:252:in `json'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/js-routes-1.3.3/lib/js_routes.rb:111:in `generate'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/js-routes-1.3.3/lib/js_routes.rb:64:in `generate'
/home/nepto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/js-routes-1.3.3/app/assets/javascripts/js-routes.js.erb:2:in `_evaluate_template'
~~~

-----------------------

I found the source of the problem here: https://github.com/railsware/js-routes/blob/v1.3.3/lib/js_routes.rb#L111-L111

When `@options[:serializer]` is not present `json(nil)` is being called. I think the root of the problem is you expect `JSON.generate(nil)` to return `"null"`, but it raises the mentioned error instead. 

~~~ruby
JSON.generate nil
=> TypeError: nil not allowed.
~~~

**Comment by nicooga** [comment]
I solved the issue. I was using the gem 'oj' and 'oj_mimic_json' to optimize JSON redering. This gem seems to monkey patch the method `JSON.generate` and causes the error.
Solved the problem by removing this gems.

**Comment by le0pard** [comment]
@nicooga I am using this versions and all works good with js-routes:
```
    oj (2.18.5)
    oj_mimic_json (1.0.1)
```
