### ISSUE TITLE
URI-encoding of route parts

### ISSUE THREAD

**Issue by orhantoy** [railsware/js-routes#243]
Hey 👋 

I noticed that route parts are not URI-encoded. I made a spec to to confirm the behavior

```diff
diff --git a/spec/js_routes/rails_routes_compatibility_spec.rb b/spec/js_routes/rails_routes_compatibility_spec.rb
index d26491f..9906ec0 100644
--- a/spec/js_routes/rails_routes_compatibility_spec.rb
+++ b/spec/js_routes/rails_routes_compatibility_spec.rb
@@ -111,6 +111,9 @@ describe JsRoutes, "compatibility with Rails"  do
     it "should support route with parameters" do
       expect(evaljs("Routes.blog_app_post_path(1)")).to eq(blog_routes.post_path(1))
     end
+    it "should support route with parameters containing symbols that need URI-encoding" do
+      expect(evaljs("Routes.blog_app_post_path('#hello')")).to eq(blog_routes.post_path('#hello'))
+    end
     it "should support root path" do
       expect(evaljs("Routes.blog_app_root_path()")).to eq(blog_routes.root_path)
     end
```

which currently fails

```
Failures:

  1) JsRoutes compatibility with Rails with rails engines should support route with parameters containing symbols that need URI-encoding
     Failure/Error: expect(evaljs("Routes.blog_app_post_path('#hello')")).to eq(blog_routes.post_path('#hello'))

       expected: "/blog/posts/%23hello"
            got: "/blog/posts/#hello"

       (compared using ==)
     # ./spec/js_routes/rails_routes_compatibility_spec.rb:115:in `block (3 levels) in <top (required)>'

Finished in 2.32 seconds (files took 0.57648 seconds to load)
160 examples, 1 failure

Failed examples:

rspec ./spec/js_routes/rails_routes_compatibility_spec.rb:114 # JsRoutes compatibility with Rails with rails engines should support route with parameters containing symbols that need URI-encoding
```

Is this an intentional choice by this lib? I would expect the behavior to match the Rails URL helpers. But I also understand that changing this could potentially break other people's use of `js-routes`, in the case where they are doing the URI-encoding themselves.

**Comment by le0pard** [comment]
@orhantoy 

After some try (https://github.com/railsware/js-routes/commit/dd6c63f34ba6953bbc11dd2e0ce6cdbdbcb954e2) I get fail in another routes:

```
1) JsRoutes compatibility with Rails with rails engines should support route with parameters containing symbols that need URI-encoding and have slashes
     Failure/Error: expect(evaljs("Routes.blog_app_post_path('#he/ll/o')")).to eq(blog_routes.post_path('#he/ll/o'))

       expected: "/blog/posts/%23he%2Fll%2Fo"
            got: "/blog/posts/%23he/ll/o"

       (compared using ==)
```

If encode everything, even `/`, we get problems in another routes:

```
 3) JsRoutes compatibility with Rails routes globbing should support routes globbing as array with optional params
     Failure/Error: expect(evaljs("Routes.book_path([1, 2, 3, 5], 1, {c: '1'})")).to eq(test_routes.book_path([1, 2, 3, 5], 1, { :c => "1" }))

       expected: "/books/1/2/3/5/1?c=1"
            got: "/books/1%2F2%2F3%2F5/1?c=1"

       (compared using ==)
     # ./spec/js_routes/rails_routes_compatibility_spec.rb:188:in `block (3 levels) in <top (required)>'

  4) JsRoutes compatibility with Rails routes globbing should support routes globbing in book_title route as array
     Failure/Error: expect(evaljs("Routes.book_title_path('john', ['thrillers', 'comedian'])")).to eq(test_routes.book_title_path('john', ['thrillers', 'comedian']))

       expected: "/books/john/thrillers/comedian"
            got: "/books/john/thrillers%2Fcomedian"

       (compared using ==)
     # ./spec/js_routes/rails_routes_compatibility_spec.rb:192:in `block (3 levels) in <top (required)>'

  5) JsRoutes compatibility with Rails routes globbing should support routes globbing in book_title route as array with optional params
     Failure/Error: expect(evaljs("Routes.book_title_path('john', ['thrillers', 'comedian'], {some_key: 'some_value'})")).to eq(test_routes.book_title_path('john', ['thrillers', 'comedian'], {:some_key => 'some_value'}))

       expected: "/books/john/thrillers/comedian?some_key=some_value"
            got: "/books/john/thrillers%2Fcomedian?some_key=some_value"

       (compared using ==)
```

**Comment by iurevych** [comment]
Hey guys, our upgrade now takes too long because of this major breaking change. We were utilizing this as a feature on our end. Is it possible to make it an option instead?

**Comment by le0pard** [comment]
@iurevych js-routes should work as rails routes. Just downgrade to previous version.

**Comment by iurevych** [comment]
Hi @le0pard here is what I’m getting in rails console:
```shell
2.6.1 :008 > app.site_path(":site_id")
 => "/sites/:site_id"
```

Here is what I’m getting now with js-routes 1.4.5:
```js
Routes.site_path(':site_id') => "/sites/%3Asite_id"
```

Do you think this is a consistent behavior?

**Comment by le0pard** [comment]
@iurevych nope. Just create test case, as it was added to this issue (with fix will be even better)

**Comment by orhantoy** [comment]
@iurevych Good catch. The difference is in how the segment (`:site_id`) is escaped in Rails

```ruby
ActionDispatch::Journey::Format::ESCAPE_SEGMENT.call(':site_id')
# => ":site_id"
```

vs in JS as you show, where `encodeURIComponent` is doing the encoding/escaping.

**Comment by iurevych** [comment]
@le0pard I can only think of reverting this PR unfortunately. Right now we can’t upgrade to js-routes 1.4.5 in an easy way because our SPA heavily depends on JS Routes. React routes are formed like so:
```js
Routes.site_path(':site_id') // regular React routes
Routes.site_path('.+') // for regex
```
Both examples fail now in our application.

**Comment by bogdan** [comment]
Rails implementation has this comment:

``` ruby
        # URI path and fragment escaping
        # https://tools.ietf.org/html/rfc3986
```

Lets figure out what RFC tell about `:` escaping.

**Comment by le0pard** [comment]
Possible solution: https://github.com/railsware/js-routes/pull/245
