### ISSUE TITLE
undefined method `register_preprocessor' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by vermaxik** [railsware/js-routes#271]
Hi here,

after Rails update to 6.1.3.2 (from 6.1.3.1), assets compiling doesn't work

It raises issue in `js_routes/engine.rb:57`:

```
js-routes-1.4.4/lib/js_routes/engine.rb:57:in `block in <class:Engine>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /Users/Maksym/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Maksym/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
	from /Users/Maksym/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
```

I can't event start the `rails console`. Could you please take a look? 

Thank you!

**Comment by vermaxik** [comment]
Oops, closed the PR, because wasn't on last version of gem. Confused with 1.4.4 and 1.4.14, sorry for that.
