### ISSUE TITLE
NameError: uninitialized constant JsRoutes::JsRoute

### ISSUE THREAD

**Issue by katerberg** [railsware/js-routes#299]
When trying to use a filtered JsRoute (which worked in 2.2.0) in version 2.2.3, I get the following error.

I assume something was changed in the interface, but I don't know the inner workings of how the Classes are exposed to understand where it should be retrieved now.

How do we access a route class in 2.2.3?

## Code

```
class FilteredJsRoute < JsRoutes::JsRoute
```

## Error

```
NameError: uninitialized constant JsRoutes::JsRoute
/Users/username/src/repofolder/config/initializers/js_routes.rb:1:in `<main>'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
/Users/username/.rvm/gems/ruby-2.7.5/gems/activesupport-6.0.4.4/lib/active_support/notifications.rb:182:in `instrument'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/engine.rb:665:in `load_config_initializer'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/engine.rb:624:in `each'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:32:in `run'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:50:in `each'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/application.rb:363:in `initialize!'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/railtie.rb:190:in `public_send'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/railtie.rb:190:in `method_missing'
/Users/username/src/repofolder/config/environment.rb:5:in `<main>'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/username/.rvm/gems/ruby-2.7.5/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/application.rb:339:in `require_environment!'
/Users/username/src/repofolder/config/monkey_patches.rb:18:in `block in run_tasks_blocks'
/Users/username/.rvm/gems/ruby-2.7.5/gems/airbrake-12.0.0/lib/airbrake/rake.rb:17:in `execute'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/command.rb:48:in `invoke'
/Users/username/.rvm/gems/ruby-2.7.5/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<main>'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/username/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => js:repofolder_routes => environment
(See full trace by running task with --trace)
```

**Comment by bogdan** [comment]
I am not sure what is `JsRoutes::JsRoute` is an internal class that is not supposed to be extended. Its API will change in a backward incompatible way. If you still want to extend it, FYI it was renamed to `JsRoutes::Route`.  But I'd better understand the reason you had to extend builtin class and find a way to reach same functionality with options and configuration.

**Comment by bogdan** [comment]
No followup, closing...

**Comment by katerberg** [comment]
Sorry about not getting back to you. I can get you more details if you're interested, but I think it's okay to say that this just is something we're doing wrong and we should spend the time to dig into it a bit more.

**Comment by bogdan** [comment]
Details would be fun to hear.

**Comment by katerberg** [comment]
We use:

```
class FilteredJsRoute < JsRoutes::JsRoute
  def initialize(configuration, route, parent_route = nil, select = nil)
    super(configuration, route, parent_route)
    @select = select
  end

  def match_configuration?
    wrapper = ActionDispatch::Routing::RouteWrapper.new(route)
    @select.any? { |regex| regex.match?(wrapper.path) }
  end
end

class FilteredJsRoutes < JsRoutes
  def select(select)
    @select = select
    self
  end

  def route_helpers_if_match(route, parent_route = nil)
    FilteredJsRoute.new(@configuration, route, parent_route, @select).helpers
  end
end
```

to allow us to use a filtered route list to ensure that any internal routes (coming out of our monolith) are not exposed to the external package. This is because we use the same monolith, and have flags to ensure that the code cannot expose internal things for external servers.

`FilteredJsRoutes.new(file: Rails.root.join('path/to/internal_routes.js')).select([%r{^/internalstuff}]).generate!`

**Comment by bogdan** [comment]
There are `exclude` and `include` options that allow to filter out routes. However, I always doubt if it is implemented the right way: it seems more logical to filter routes based on `path` like in your solution but not by route helper name like for `include/exclude` options. So, I am open for a discussion to implement options to filter routes by path
