### ISSUE TITLE
JsRoutes namespace option can only be used if module_type is nil

### ISSUE THREAD

**Issue by adeherdt-r7** [railsware/js-routes#316]
Hello,

We are in the middle of upgrading a Rails project, and part of the work is upgrading `js-routes` from 1.4 to the latest version.
We are still locked to `sprockets`, so until we make the swap to something like `bun` with `js-bundling`, we have no alternative at the moment.

I tried following the guide for Sprockets, and did the following:

1. Added `config/initializers/js_routes.rb` initializer with setting `module_type = nil` and `namespace = 'Routes'`
2. Added `task "assets:precompile" => "js:routes:typescript"` to the `Rakefile`
3. Added `//= require js-routes` to the `app/assets/javascript/application.js`

And while I can spin up the application in `development` mode just fine with everything seemingly working, the `assets:precompile` command keeps failing with the following:

```
~/Source/pro/ui git:[MS-9572-update-js-routes] bundle exec rails assets:precompile
rails aborted!
JsRoutes namespace option can only be used if module_type is nil

Tasks: TOP => assets:precompile => js:routes:typescript
(See full trace by running task with --trace)
```

Am I missing something for the Sprockets approach to make this work?

**Comment by adeherdt-r7** [comment]
I added some manual debug output:

```
~/Source/pro/ui git:[MS-9572-update-js-routes] bundle exec rails assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Invoke db:config:restore (first_time)
** Execute db:config:restore
** Execute environment
DEBUG JsRoutes: module_type = ESM
DEBUG JsRoutes: module_type = 
** Invoke bower:before_precompile (first_time)
** Execute bower:before_precompile
** Invoke js:routes:typescript (first_time)
** Invoke js:routes (first_time)
** Invoke environment 
** Execute js:routes
DEBUG JsRoutes: module_type = NIL
** Execute js:routes:typescript
DEBUG JsRoutes: module_type = DTS
rails aborted!
JsRoutes namespace option can only be used if module_type is nil
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes/configuration.rb:108:in `verify'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes/configuration.rb:90:in `normalize_and_verify'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes/configuration.rb:41:in `assign'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes/configuration.rb:50:in `merge'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes/instance.rb:13:in `initialize'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes.rb:29:in `new'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes.rb:29:in `generate!'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/js_routes.rb:38:in `definitions!'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.8/lib/tasks/js_routes.rake:11:in `block (3 levels) in <top (required)>'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:241:in `each'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/command.rb:51:in `invoke'
/home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => assets:precompile => js:routes:typescript
```

The "problem" is the TypeScript invocation. We do not run TypeScript whatsoever in our application.
Is there a possibility to disable this?

**Comment by adeherdt-r7** [comment]
Okay never mind, I found the issue.

The Rakefile should be 
```
# Update js-routes file before javascript build
task "assets:precompile" => "js:routes"
```

**Comment by bogdan** [comment]
I've just released a fix to the problem with using middleware for non-typescript setup. Try the latest version.

#315

**Comment by adeherdt-r7** [comment]
Ah cheers, will give it a spin and see how it behaves!

**Comment by adeherdt-r7** [comment]
Adding the middleware back to the `development.rb` results in the following error now:

```
09:08:41 web.1       | 2024-10-03 09:08:40 +0200 Using rack adapter
09:08:44 web.1       | /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'app': Expected type T.proc.params(a0: T::Hash[String, T.untyped]).returns(T::Array[T.untyped]), got type ActionDispatch::Routing::RouteSet with value #<ActionDispatch::Routing::RouteSet:0x0000746700b4e0c0> (TypeError)
09:08:44 web.1       | Caller: /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:37
09:08:44 web.1       | Definition: /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/js-routes-2.2.9/lib/js_routes/middleware.rb:15 (JsRoutes::Middleware#initialize)
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/configuration.rb:303:in `call_validation_error_handler'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/private/methods/call_validation.rb:310:in `report_error'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/private/methods/call_validation.rb:215:in `validate_call'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/sorbet-runtime-0.5.11592/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:37:in `new'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:37:in `build'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:166:in `block in build'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:162:in `each'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:162:in `inject'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/actionpack-7.0.8.4/lib/action_dispatch/middleware/stack.rb:162:in `build'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/engine.rb:516:in `block in app'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/engine.rb:512:in `synchronize'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/engine.rb:512:in `app'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/initializable.rb:32:in `instance_exec'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/initializable.rb:32:in `run'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/initializable.rb:61:in `block in run_initializers'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:347:in `each'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:347:in `call'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
09:08:44 web.1       | 	from /home/noel/.rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/initializable.rb:60:in `run_initializers'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/application.rb:372:in `initialize!'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/railtie.rb:226:in `public_send'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/railties-7.0.8.4/lib/rails/railtie.rb:226:in `method_missing'
09:08:44 web.1       | 	from /home/noel/Source/pro/ui/config/environment.rb:5:in `<top (required)>'
09:08:44 web.1       | 	from /home/noel/Source/pro/ui/config.ru:3:in `require'
09:08:44 web.1       | 	from /home/noel/Source/pro/ui/config.ru:3:in `block in <main>'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rack-2.2.9/lib/rack/builder.rb:125:in `instance_eval'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/rack-2.2.9/lib/rack/builder.rb:125:in `initialize'
09:08:44 web.1       | 	from /home/noel/Source/pro/ui/config.ru:1:in `new'
09:08:44 web.1       | 	from /home/noel/Source/pro/ui/config.ru:1:in `<main>'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `eval'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `load'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/rack/adapter/loader.rb:42:in `for'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/thin/controllers/controller.rb:170:in `load_adapter'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/thin/controllers/controller.rb:74:in `start'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/bin/thin:25:in `load'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/bin/thin:25:in `<main>'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/bin/ruby_executable_hooks:22:in `eval'
09:08:44 web.1       | 	from /home/noel/.rvm/gems/ruby-3.1.6@pro/bin/ruby_executable_hooks:22:in `<main>'
```

on boot.

**Comment by adeherdt-r7** [comment]
Also the generator does not work either in our setup:

```
~/Source/pro/ui git:[MS-9572-update-js-routes] bundle exec rails generate js_routes:middleware
Could not find "initializer.rb" in any of your source paths. Please invoke JsRoutes::Generators::Middleware.source_root(PATH) with the PATH containing your templates. Currently you have no source paths.
```

**Comment by bogdan** [comment]
Huh, JS has so many legacy that we never know how one legacy would suppose to interact with another legacy.

I tried to fix all the concerns I could.

You need to use the following in your Rakefile:

```
task "assets:precompile" => "js:routes"
```

Typescript can only be supported if you are using `ESM` module. Now, the generator will update `Rakefile` according based on if you have ESM module setup or not.

**Comment by adeherdt-r7** [comment]
Yeah I have that in the Rakefile, and the `assets:precompile` works just fine with that setup.
The Middleware doesn't work at all for us, but we can manually regenerate the `routes.js` in development mode when needed, so that's not a big issue for us, it's just weird behavior.

But it could also be on our side cause I'm not entirely sure the app behaves as a standard Rails app, so I'm fine with closing this for now, and give this another shot at proper integration once we switched to full typescript support.

**Comment by bogdan** [comment]
Do you get any error when using middleware? 
Does you app have any custom setup around `config/routes.rb`?

**Comment by adeherdt-r7** [comment]
I can't explain too much about the details, but we do work with multiple Rails engines that go through the same code-path.
Outside that we don't have anything custom around our routing, it's the standard routing defined in `config/routes.rb`, just that the engine is either the Rails application itself, or a Rails engine. But this shouldn't affect the behavior as both are still Rails code.

```
begin
  engine = <standard Rails Application from application.rb>
rescue NameError
  engine = <custom class loaded by tests/cucumber>
end

engine.routes.draw do
end
```

But if I try add the middleware in `development.rb` the errors posted earlier show up, even with the configuration initializer.

**Comment by bogdan** [comment]
> But if I try add the middleware in development.rb the errors posted earlier show up, even with the configuration initializer.


That should be fixed in version 2.2.10

**Comment by adeherdt-r7** [comment]
> > But if I try add the middleware in development.rb the errors posted earlier show up, even with the configuration initializer.
> 
> That should be fixed in version 2.2.10

Just verified it, works!
That rules out the middlware issue then and everything works as expected then.
Thank you very much for the fixes on this and being on the ball with this.

**Comment by adfoster-r7** [comment]
@bogdan Sorry for the ping on this thread again; it looks like v2.2.10 of js-routes worked successfully - thanks! However updating to a newer version things fail again now:

```
** Invoke js:routes (first_time)
** Invoke environment 
** Execute js:routes
rails aborted!
JsRoutes namespace option can only be used if module_type is nil
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes/configuration.rb:155:in `verify'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes/configuration.rb:134:in `normalize_and_verify'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes/configuration.rb:73:in `assign'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes/configuration.rb:89:in `merge'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes/instance.rb:21:in `initialize'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:179:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:179:in `validate_call_skip_block_type'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:121:in `block in create_validator_slow_skip_block_type'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes.rb:39:in `new'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes.rb:39:in `generate!'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:179:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:179:in `validate_call_skip_block_type'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:121:in `block in create_validator_slow_skip_block_type'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes.rb:58:in `definitions!'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/js_routes.rb:40:in `generate!'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/sorbet-runtime-0.5.11734/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/js-routes-2.3.0/lib/tasks/js_routes.rake:5:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:241:in `each'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/railties-7.0.8.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/railties-7.0.8.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/railties-7.0.8.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/railties-7.0.8.6/lib/rails/command.rb:51:in `invoke'
/Users/user/.rvm/gems/ruby-3.2.5@pro/gems/railties-7.0.8.6/lib/rails/commands.rb:18:in `<top (required)>'
<internal:/Users/user/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/user/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => assets:precompile => js:routes
```

I was able to confirm things broke updating from 2.2.10 to 2.3.0, and all versions through to 2.3.4 produce the same error

From the [CHANGELOG](https://github.com/railsware/js-routes/blob/83d65bbe363255871bdd115e14aa70f83b0f35cb/CHANGELOG.md#230) I noticed the line:

> Drop support of Rails 4.x

The application is Rails 7.x, but still running sprockets 3 - so potentially that might be the issue? Or potentially it's an unexpected regression - any help appreciated! 🎉

**Comment by adfoster-r7** [comment]
@bogdan Would be it possible to have a new release for that bug fix? Would love to be running on the latest code 🤞
